// Generated by cs2-sdk - https://cs2-sdk.com
// Resolved global RVAs, merged from the offset (pattern-scan) and
// Pattern (rip-relative) passes into one tree: offsets::<module>::Name
// (no dw / _ptr affixes).
#pragma once

#include <cstddef>
#include <cstdint>

namespace offsets {
    namespace animationsystem {
        constexpr std::ptrdiff_t AnimationSystemUtils_001 = 0x83F6D8;
        constexpr std::ptrdiff_t AnimationSystem_001 = 0x8375F8;
        constexpr std::ptrdiff_t pAnimationSystemUtils = 0x83F6B8;
    }
    namespace client {
        constexpr std::ptrdiff_t CInputPtrGlobal = 0x223A320;
        constexpr std::ptrdiff_t CSGOInput = 0x2578160;
        constexpr std::ptrdiff_t ClientBugBugServic001_Client = 0x22317E0;
        constexpr std::ptrdiff_t ClientToolsInfo_001 = 0x22317B0;
        constexpr std::ptrdiff_t EmptyWorldService001_Client = 0x2215220;
        constexpr std::ptrdiff_t EntityList = 0x2717828;
        constexpr std::ptrdiff_t GameClientExports001 = 0x222E458;
        constexpr std::ptrdiff_t GameEntitySystem = 0x2717828;
        constexpr std::ptrdiff_t GameEntitySystem_highestEntityIndex = 0x2120;
        constexpr std::ptrdiff_t GameRules = 0x255EE50;
        constexpr std::ptrdiff_t GetAbsOrigin = 0x2197E0;
        constexpr std::ptrdiff_t GetBombsiteACenter = 0x8CCE70;
        constexpr std::ptrdiff_t GetBombsiteBCenter = 0x8CCED0;
        constexpr std::ptrdiff_t GlobalVars = 0x222DE98;
        constexpr std::ptrdiff_t GlowManager = 0x255EE60;
        constexpr std::ptrdiff_t LegacyGameUI001 = 0x223E0E0;
        constexpr std::ptrdiff_t LocalPlayerController = 0x253A068;
        constexpr std::ptrdiff_t LocalPlayerPawn = 0x2562808;
        constexpr std::ptrdiff_t ManageGlowSceneObject = 0xB77DC0;
        constexpr std::ptrdiff_t PlantedC4 = 0x24CA930;
        constexpr std::ptrdiff_t Prediction = 0x2562710;
        constexpr std::ptrdiff_t Sensitivity = 0x255F998;
        constexpr std::ptrdiff_t Sensitivity_sensitivity = 0x58;
        constexpr std::ptrdiff_t SetItemItemIdFunction = 0xE5A9F0;
        constexpr std::ptrdiff_t SetSceneObjectAttributeFloat4 = 0x16AB80;
        constexpr std::ptrdiff_t Source2Client002 = 0x255C3A0;
        constexpr std::ptrdiff_t Source2ClientConfig001 = 0x24B92B0;
        constexpr std::ptrdiff_t Source2ClientPrediction001 = 0x2562710;
        constexpr std::ptrdiff_t Source2ClientUI001 = 0x223C960;
        constexpr std::ptrdiff_t TransformScale3dVMT = 0x1CBCDD0;
        constexpr std::ptrdiff_t TransformTranslate3dVMT = 0x1CBCD90;
        constexpr std::ptrdiff_t ViewAngles = 0x25787E8;
        constexpr std::ptrdiff_t ViewMatrix = 0x2567FA0;
        constexpr std::ptrdiff_t ViewRender = 0x2568968;
        constexpr std::ptrdiff_t WeaponC4 = 0x24C6AF0;
        constexpr std::ptrdiff_t pCSGOInputInstance = 0x2578160;
        constexpr std::ptrdiff_t pCSInventoryManager = 0x24D5AC0;
        constexpr std::ptrdiff_t pClientMode = 0x2575EC0;
        constexpr std::ptrdiff_t pCvar = 0x2799C78;
        constexpr std::ptrdiff_t pDynamicLightManager = 0x2557328;
        constexpr std::ptrdiff_t pEconItemSystem = 0x25F10C0;
        constexpr std::ptrdiff_t pEntitySystem = 0x23B8870;
        constexpr std::ptrdiff_t pGameEntitySystem = 0x2717828;
        constexpr std::ptrdiff_t pGameEventManager = 0x25489B0;
        constexpr std::ptrdiff_t pGameRules = 0x255EE50;
        constexpr std::ptrdiff_t pGameTraceManager = 0x2225138;
        constexpr std::ptrdiff_t pGlobalVariables = 0x222DE98;
        constexpr std::ptrdiff_t pGlowManager = 0x255EE60;
        constexpr std::ptrdiff_t pHudPanel = 0x25D2F78;
        constexpr std::ptrdiff_t pInterpolationPhase = 0x21BD0A8;
        constexpr std::ptrdiff_t pInventoryCategoryTree = 0x25EFE30;
        constexpr std::ptrdiff_t pLocalPlayerController = 0x253A068;
        constexpr std::ptrdiff_t pMainMenuPanel = 0x25C6558;
        constexpr std::ptrdiff_t pMatchFramework = 0x2799D90;
        constexpr std::ptrdiff_t pMatchmakingReservation = 0x25794D8;
        constexpr std::ptrdiff_t pMaterialManager = 0x2799ED0;
        constexpr std::ptrdiff_t pParticleManager = 0x22252E8;
        constexpr std::ptrdiff_t pPlantedC4s = 0x24CA930;
        constexpr std::ptrdiff_t pPrediction = 0x2562710;
        constexpr std::ptrdiff_t pPredictionPlayer = 0x2553A68;
        constexpr std::ptrdiff_t pPredictionRandomSeed = 0x21C12A0;
        constexpr std::ptrdiff_t pRenderGameSystem = 0x23BA0E8;
        constexpr std::ptrdiff_t pSensitivity = 0x255F998;
        constexpr std::ptrdiff_t pUIInventory = 0x25285E8;
        constexpr std::ptrdiff_t pUiEngine = 0x2730E60;
        constexpr std::ptrdiff_t pViewRender = 0x2568968;
        constexpr std::ptrdiff_t pViewToProjectionMatrix = 0x2567F60;
        constexpr std::ptrdiff_t pWeaponC4 = 0x24C6AF0;
        constexpr std::ptrdiff_t pWeaponRecoilTable = 0x2217718;
        constexpr std::ptrdiff_t pWorldToProjectionMatrix = 0x2567FA0;
    }
    namespace engine2 {
        constexpr std::ptrdiff_t BenchmarkService001 = 0x622C80;
        constexpr std::ptrdiff_t BugBugService001 = 0x622D80;
        constexpr std::ptrdiff_t BugService001 = 0x8DB7F0;
        constexpr std::ptrdiff_t BuildNumber = 0x61CFE8;
        constexpr std::ptrdiff_t ClientServerEngineLoopService_001 = 0x91CE30;
        constexpr std::ptrdiff_t ClientServerSharedHandleSystem001 = 0x91C440;
        constexpr std::ptrdiff_t EngineGameUI001 = 0x6206E0;
        constexpr std::ptrdiff_t EngineServiceMgr001 = 0x91C700;
        constexpr std::ptrdiff_t GameEventSystemClientV001 = 0x91C9E0;
        constexpr std::ptrdiff_t GameEventSystemServerV001 = 0x91CB10;
        constexpr std::ptrdiff_t GameResourceServiceClientV001 = 0x622DC0;
        constexpr std::ptrdiff_t GameResourceServiceServerV001 = 0x622E20;
        constexpr std::ptrdiff_t GameUIService_001 = 0x8DBC40;
        constexpr std::ptrdiff_t HostStateMgr001 = 0x623540;
        constexpr std::ptrdiff_t INETSUPPORT_001 = 0x61BC30;
        constexpr std::ptrdiff_t InputService_001 = 0x8DBF20;
        constexpr std::ptrdiff_t KeyValueCache001 = 0x6235F0;
        constexpr std::ptrdiff_t MapListService_001 = 0x91AD90;
        constexpr std::ptrdiff_t NetworkClientService_001 = 0x91AF20;
        constexpr std::ptrdiff_t NetworkGameClient = 0x91AFC0;
        constexpr std::ptrdiff_t NetworkGameClient_clientTickCount = 0x398;
        constexpr std::ptrdiff_t NetworkGameClient_deltaTick = 0x24C;
        constexpr std::ptrdiff_t NetworkGameClient_isBackgroundMap = 0x2C143F;
        constexpr std::ptrdiff_t NetworkGameClient_localPlayer = 0xF8;
        constexpr std::ptrdiff_t NetworkGameClient_maxClients = 0x240;
        constexpr std::ptrdiff_t NetworkGameClient_serverTickCount = 0x24C;
        constexpr std::ptrdiff_t NetworkGameClient_signOnState = 0x230;
        constexpr std::ptrdiff_t NetworkP2PService_001 = 0x91B260;
        constexpr std::ptrdiff_t NetworkServerService_001 = 0x91B410;
        constexpr std::ptrdiff_t NetworkService_001 = 0x622F90;
        constexpr std::ptrdiff_t RenderService_001 = 0x91B680;
        constexpr std::ptrdiff_t ScreenshotService001 = 0x91B940;
        constexpr std::ptrdiff_t SimpleEngineLoopService_001 = 0x623650;
        constexpr std::ptrdiff_t SoundService_001 = 0x622FD0;
        constexpr std::ptrdiff_t Source2EngineToClient001 = 0x61FFF0;
        constexpr std::ptrdiff_t Source2EngineToClientStringTable001 = 0x620050;
        constexpr std::ptrdiff_t Source2EngineToServer001 = 0x6200C8;
        constexpr std::ptrdiff_t Source2EngineToServerStringTable001 = 0x6200F0;
        constexpr std::ptrdiff_t SplitScreenService_001 = 0x6232B0;
        constexpr std::ptrdiff_t StatsService_001 = 0x91BC80;
        constexpr std::ptrdiff_t ToolService_001 = 0x6233B0;
        constexpr std::ptrdiff_t VENGINE_GAMEUIFUNCS_VERSION005 = 0x620770;
        constexpr std::ptrdiff_t VProfService_001 = 0x6233F0;
        constexpr std::ptrdiff_t WindowHeight = 0x91F334;
        constexpr std::ptrdiff_t WindowWidth = 0x91F330;
        constexpr std::ptrdiff_t pBuildNumber = 0x61CFE8;
        constexpr std::ptrdiff_t pFrameInputRing = 0x91D000;
        constexpr std::ptrdiff_t pFrameInputRingIndex = 0x91CCEC;
        constexpr std::ptrdiff_t pNetworkGameClient = 0x91AFC0;
        constexpr std::ptrdiff_t pPVSManager = 0x6236A0;
        constexpr std::ptrdiff_t pWindowHeight = 0x91F334;
        constexpr std::ptrdiff_t pWindowWidth = 0x91F330;
    }
    namespace filesystem_stdio {
        constexpr std::ptrdiff_t VAsyncFileSystem2_001 = 0x214610;
        constexpr std::ptrdiff_t VFileSystem017 = 0x2143D0;
    }
    namespace host {
        constexpr std::ptrdiff_t DebugDrawQueueManager001 = 0x13FF70;
        constexpr std::ptrdiff_t GameModelInfo001 = 0x13FFB0;
        constexpr std::ptrdiff_t GameSystem2HostHook = 0x13FFF0;
        constexpr std::ptrdiff_t HostUtils001 = 0x14F900;
        constexpr std::ptrdiff_t PredictionDiffManager001 = 0x140100;
        constexpr std::ptrdiff_t SaveRestoreDataVersion001 = 0x140230;
        constexpr std::ptrdiff_t SinglePlayerSharedMemory001 = 0x140260;
        constexpr std::ptrdiff_t Source2Host001 = 0x1402D0;
    }
    namespace imemanager {
        constexpr std::ptrdiff_t IMEManager001 = 0x37AA0;
    }
    namespace inputsystem {
        constexpr std::ptrdiff_t InputStackSystemVersion001 = 0x44E90;
        constexpr std::ptrdiff_t InputSystem = 0x46BC0;
        constexpr std::ptrdiff_t InputSystemVersion001 = 0x46BC0;
        constexpr std::ptrdiff_t pInputSystemSvc = 0x46BC0;
    }
    namespace localize {
        constexpr std::ptrdiff_t Localize_001 = 0x59120;
    }
    namespace matchmaking {
        constexpr std::ptrdiff_t GameTypes = 0x1B0FD0;
        constexpr std::ptrdiff_t GameTypes001 = 0x1B0FD0;
        constexpr std::ptrdiff_t MATCHFRAMEWORK_001 = 0x1B90A0;
    }
    namespace materialsystem2 {
        constexpr std::ptrdiff_t FontManager_001 = 0x1638E0;
        constexpr std::ptrdiff_t MaterialUtils_001 = 0x14BD30;
        constexpr std::ptrdiff_t PostProcessingSystem_001 = 0x14BC60;
        constexpr std::ptrdiff_t TextLayout_001 = 0x14BCC0;
        constexpr std::ptrdiff_t VMaterialSystem2_001 = 0x163530;
    }
    namespace meshsystem {
        constexpr std::ptrdiff_t MeshSystem001 = 0x180AB0;
    }
    namespace navsystem {
        constexpr std::ptrdiff_t NavSystem001 = 0x12C000;
    }
    namespace networksystem {
        constexpr std::ptrdiff_t FlattenedSerializersVersion001 = 0x277A50;
        constexpr std::ptrdiff_t NetworkMessagesVersion001 = 0x2A3F30;
        constexpr std::ptrdiff_t NetworkSystemVersion001 = 0x2911A0;
        constexpr std::ptrdiff_t SerializedEntitiesVersion001 = 0x291290;
        constexpr std::ptrdiff_t pNetworkSystem = 0x2911A0;
    }
    namespace panorama {
        constexpr std::ptrdiff_t PanoramaUIEngine001 = 0x5895F0;
    }
    namespace panorama_text_pango {
        constexpr std::ptrdiff_t PanoramaTextServices001 = 0x2BA9D0;
    }
    namespace panoramauiclient {
        constexpr std::ptrdiff_t PanoramaUIClient001 = 0x270710;
    }
    namespace particles {
        constexpr std::ptrdiff_t GetParticleManager = 0x5FD890;
        constexpr std::ptrdiff_t ParticleSystemMgr003 = 0x65AEB0;
    }
    namespace pulse_system {
        constexpr std::ptrdiff_t IPulseSystem_001 = 0x238120;
    }
    namespace rendersystemdx11 {
        constexpr std::ptrdiff_t RenderDeviceMgr001 = 0x4342F0;
        constexpr std::ptrdiff_t RenderUtils_001 = 0x434BD0;
        constexpr std::ptrdiff_t VRenderDeviceMgrBackdoor001 = 0x434390;
    }
    namespace resourcesystem {
        constexpr std::ptrdiff_t ResourceSystem013 = 0x892B0;
    }
    namespace scenefilecache {
        constexpr std::ptrdiff_t ResponseRulesCache001 = 0x11D350;
        constexpr std::ptrdiff_t SceneFileCache002 = 0x11D478;
    }
    namespace scenesystem {
        constexpr std::ptrdiff_t RenderingPipelines_001 = 0x675A00;
        constexpr std::ptrdiff_t SceneSystem_002 = 0x91FB20;
        constexpr std::ptrdiff_t SceneUtils_001 = 0x676760;
        constexpr std::ptrdiff_t pSceneLightDataQueue = 0x921A28;
        constexpr std::ptrdiff_t pSceneSystem = 0x91FB20;
    }
    namespace schemasystem {
        constexpr std::ptrdiff_t SchemaSystem_001 = 0x76710;
        constexpr std::ptrdiff_t pSchemaSystem = 0x76710;
    }
    namespace server {
        constexpr std::ptrdiff_t EmptyWorldService001_Server = 0x1E09100;
        constexpr std::ptrdiff_t EntitySubclassUtilsV001 = 0x1DB8BC0;
        constexpr std::ptrdiff_t NavGameTest001 = 0x1E50DC8;
        constexpr std::ptrdiff_t ServerToolsInfo_001 = 0x1E2FCB8;
        constexpr std::ptrdiff_t Source2GameClients001 = 0x1E2F1E0;
        constexpr std::ptrdiff_t Source2GameDirector001 = 0x1F99730;
        constexpr std::ptrdiff_t Source2GameEntities001 = 0x1E2F460;
        constexpr std::ptrdiff_t Source2Server001 = 0x1E2F2A0;
        constexpr std::ptrdiff_t Source2ServerConfig001 = 0x2114C98;
        constexpr std::ptrdiff_t customnavsystem001 = 0x1DA64F0;
    }
    namespace soundsystem {
        constexpr std::ptrdiff_t SoundBugBugService001_Client = 0x535BB0;
        constexpr std::ptrdiff_t SoundOpSystem001 = 0x535A90;
        constexpr std::ptrdiff_t SoundOpSystemEdit001 = 0x5359A0;
        constexpr std::ptrdiff_t SoundSystem = 0x535350;
        constexpr std::ptrdiff_t SoundSystem001 = 0x535350;
        constexpr std::ptrdiff_t SoundSystem_engineViewData = 0x6C;
        constexpr std::ptrdiff_t VMixEditTool001 = 0x5943D7F;
        constexpr std::ptrdiff_t pSoundChannels = 0x657C68;
        constexpr std::ptrdiff_t pSoundSystem = 0x535350;
    }
    namespace steamaudio {
        constexpr std::ptrdiff_t SteamAudio001 = 0x35C1A0;
    }
    namespace tier0 {
        constexpr std::ptrdiff_t TestScriptMgr001 = 0x3A1960;
        constexpr std::ptrdiff_t VEngineCvar007 = 0x3AC670;
        constexpr std::ptrdiff_t VProcessUtils002 = 0x3A1820;
        constexpr std::ptrdiff_t VStringTokenSystem001 = 0x3D3300;
        constexpr std::ptrdiff_t pCVar = 0x3AC670;
        constexpr std::ptrdiff_t pCvarRegistry = 0x3A9568;
    }
    namespace v8system {
        constexpr std::ptrdiff_t Source2V8System001 = 0x34790;
    }
    namespace vphysics2 {
        constexpr std::ptrdiff_t VPhysics2_Interface_001 = 0x460E60;
    }
    namespace vscript {
        constexpr std::ptrdiff_t VScriptManager010 = 0x13E430;
    }
    namespace worldrenderer {
        constexpr std::ptrdiff_t WorldRendererMgr001 = 0x236D00;
    }
}
