#pragma once
#include <string>
#include <unordered_map>

namespace weapon_icons {

static std::unordered_map<std::string, std::string> icon_table = {
    {"deagle",          "\xEE\x80\x81"},
    {"elite",           "\xEE\x80\x82"},
    {"fiveseven",       "\xEE\x80\x83"},
    {"glock",           "\xEE\x80\x84"},
    {"ak47",            "\xEE\x80\x87"},
    {"aug",             "\xEE\x80\x88"},
    {"awp",             "\xEE\x80\x89"},
    {"famas",           "\xEE\x80\x8A"},
    {"g3sg1",           "\xEE\x80\x8B"},
    {"galilar",         "\xEE\x80\x8D"},
    {"m249",            "\xEE\x80\xBC"},
    {"m4a1",            "\xEE\x80\x8E"},
    {"mac10",           "\xEE\x80\x91"},
    {"p90",             "\xEE\x80\xA4"},
    {"ump45",           "\xEE\x80\x98"},
    {"xm1014",          "\xEE\x80\x99"},
    {"bizon",           "\xEE\x80\x9A"},
    {"mag7",            "\xEE\x80\x9B"},
    {"negev",           "\xEE\x80\x9C"},
    {"sawedoff",        "\xEE\x80\x9D"},
    {"tec9",            "\xEE\x80\x9E"},
    {"taser",           "\xEE\x80\x9F"},
    {"hkp2000",         "\xEE\x80\x93"},
    {"mp7",             "\xEE\x80\xA1"},
    {"mp9",             "\xEE\x80\xA2"},
    {"nova",            "\xEE\x80\xA3"},
    {"p250",            "\xEE\x80\xA0"},
    {"scar20",          "\xEE\x80\xA6"},
    {"sg556",           "\xEE\x80\xA7"},
    {"ssg08",           "\xEE\x80\xA8"},
    {"knife",           "\xEE\x80\xAA"},
    {"flashbang",       "\xEE\x80\xAB"},
    {"hegrenade",       "\xEE\x80\xAC"},
    {"smokegrenade",    "\xEE\x80\xAD"},
    {"molotov",         "\xEE\x80\xAE"},
    {"decoy",           "\xEE\x80\xAF"},
    {"incgrenade",      "\xEE\x80\xB0"},
    {"c4",              "\xEE\x80\xB1"},
    {"knife_t",         "\xEE\x80\xBB"},
    {"m4a1_silencer",   "\xEE\x80\x90"},
    {"usp_silencer",    "\xEE\x80\xBD"},
    {"cz75a",           "\xEE\x80\xBF"},
    {"revolver",        "\xEE\x81\x80"},
    {"knife_bayonet",   "\xEE\x87\xB4"},
    {"knife_flip",      "\xEE\x87\xB9"},
    {"knife_gut",       "\xEE\x87\xBA"},
    {"knife_karambit",  "\xEE\x87\xBB"},
    {"knife_m9_bayonet","\xEE\x87\xBC"},
    {"knife_tactical",  "\xEE\x87\xBD"},
    {"knife_falchion",  "\xEE\x88\x80"},
    {"knife_survival_bowie", "\xEE\x88\x82"},
    {"knife_butterfly", "\xEE\x88\x83"},
    {"knife_push",      "\xEE\x88\x84"},
    {"knife_cord",      "\xEE\x80\xAA"},
    {"knife_canis",     "\xEE\x80\xAA"},
    {"knife_ursus",     "\xEE\x80\xAA"},
    {"knife_gypsy_jackknife", "\xEE\x80\xAA"},
    {"knife_outdoor",   "\xEE\x80\xAA"},
    {"knife_stiletto",  "\xEE\x80\xAA"},
    {"knife_widowmaker","\xEE\x80\xAA"},
    {"knife_skeleton",  "\xEE\x80\xAA"},
    {"knife_css",       "\xEE\x80\xAA"},
    {"knife_gg",        ""},
    {"shield",          ""},
    {"mp5sd",           ""},
};

static std::unordered_map<std::string, const char*> display_table = {
    {"deagle",          "Desert Eagle"},
    {"elite",           "Dual Berettas"},
    {"fiveseven",       "Five-SeveN"},
    {"glock",           "Glock-18"},
    {"ak47",            "AK-47"},
    {"aug",             "AUG"},
    {"awp",             "AWP"},
    {"famas",           "FAMAS"},
    {"g3sg1",           "G3SG1"},
    {"galilar",         "Galil AR"},
    {"m249",            "M249"},
    {"m4a1",            "M4A4"},
    {"mac10",           "MAC-10"},
    {"p90",             "P90"},
    {"mp5sd",           "MP5-SD"},
    {"ump45",           "UMP-45"},
    {"xm1014",          "XM1014"},
    {"bizon",           "PP-Bizon"},
    {"mag7",            "MAG-7"},
    {"negev",           "Negev"},
    {"sawedoff",        "Sawed-Off"},
    {"tec9",            "Tec-9"},
    {"taser",           "Zeus x27"},
    {"hkp2000",         "P2000"},
    {"mp7",             "MP7"},
    {"mp9",             "MP9"},
    {"nova",            "Nova"},
    {"p250",            "P250"},
    {"shield",          "Shield"},
    {"scar20",          "SCAR-20"},
    {"sg556",           "SG 553"},
    {"ssg08",           "SSG 08"},
    {"knife",           "Knife"},
    {"knife_gg",        "Knife"},
    {"flashbang",       "Flashbang"},
    {"hegrenade",       "HE Grenade"},
    {"smokegrenade",    "Smoke Grenade"},
    {"molotov",         "Molotov"},
    {"decoy",           "Decoy"},
    {"incgrenade",      "Incendiary"},
    {"c4",              "Bomb"},
    {"knife_t",         "Knife (T)"},
    {"m4a1_silencer",   "M4A1-S"},
    {"usp_silencer",    "USP-S"},
    {"cz75a",           "CZ75-Auto"},
    {"revolver",        "R8 Revolver"},
    {"knife_bayonet",   "Bayonet"},
    {"knife_css",       "Knife"},
    {"knife_flip",      "Flip Knife"},
    {"knife_gut",       "Gut Knife"},
    {"knife_karambit",  "Karambit"},
    {"knife_m9_bayonet","M9 Bayonet"},
    {"knife_tactical",  "Tactical Knife"},
    {"knife_falchion",  "Falchion Knife"},
    {"knife_survival_bowie", "Bowie Knife"},
    {"knife_butterfly", "Butterfly Knife"},
    {"knife_push",      "Shadow Daggers"},
    {"knife_cord",      "Cord Knife"},
    {"knife_canis",     "Canis Knife"},
    {"knife_ursus",     "Ursus Knife"},
    {"knife_gypsy_jackknife", "Jack Knife"},
    {"knife_outdoor",   "Outdoor Knife"},
    {"knife_stiletto",  "Stiletto Knife"},
    {"knife_widowmaker","Widowmaker Knife"},
    {"knife_skeleton",  "Skeleton Knife"},
};

}
